name: alla
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  go_router: ^16.3.0
  flutter:
    sdk: flutter

  google_fonts: ^4.0.4
  fluttertoast: ^9.0.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  mask_text_input_formatter: ^2.0.0
  pin_input_text_field: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_icons:
  android: true
  image_path: "assets/images/logo.png"


flutter:
  assets:
    - assets/icons/
    - assets/images/

  uses-material-design: true

